sudo: false

language: php

env:
  - CODE_REVIEW=1

before_install:
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"


install:
  # Install Coder for code standard reviews.
  - $TRAVIS_BUILD_DIR/build/travis/bin/install_coder.sh

script:
  # Run Code Style validation.
  - $TRAVIS_BUILD_DIR/build/travis/bin/run_coder.sh
